baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'finsweet'

theme = 'hugo-tailwind-theme'


[author]
name = "Default Author"

[params]
  [params.logo]
    image = '/images/logo-dark.svg'
    alt = 'Finsweet'
  [params.default_hero_image]
    image = '/images/team-photo-3.png'
  [params.related_posts]
    title = 'Read more posts'

sectionPagesMenu = 'main'

[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    weight = 10
  [[menus.main]]
    name = 'Products'
    url = '/products/'
    weight = 20
  [[menus.main]]
    name = 'Pricing'
    url = '/pricing/'
    weight = 30
  [[menus.main]]
    name = 'About Us'
    url = '/about/'
    weight = 40
  [[menus.main]]
    name = 'Blog'
    url = '/blog/'
    weight = 50
  [[menus.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 60
