backend:
  name: github
  repo: avicndugu/hugo-tailwind-company
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://hugo-tailwind-company.pages.dev/
  auth_endpoint: /api/auth
publish_mode: editorial_workflow
media_folder: static/images/
public_folder: /images/
collections:
  - name: 'Posts'
    label: 'posts'
    folder: 'content/blog/'
    create: true
    editor:
      preview: true
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'home'
        label: 'Home'
        file: 'content/_index.md'
        fields:
          - { name: title, label: Title, widget: string }
          - { name: draft, label: Draft, widget: boolean, default: true }

    preview_path: /{{slug}}
