backend:
  name: github
  repo: avicndugu/hugo-tailwind-company
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://hugo-tailwind-company.pages.dev/
  auth_endpoint: /api/auth
publish_mode: editorial_workflow
media_folder: static/images/
public_folder: /images/
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'home'
        label: 'Home'
        file: 'content/_index.md'
        fields:
          - { name: 'title', label: 'Title', widget: 'string' }
          - { name: 'draft', label: 'Draft', widget: 'boolean', default: true }
          - {
              name: 'hero',
              label: 'Hero',
              widget: 'object',
              fields:
                [
                  { name: 'title', label: 'Title', widget: 'string' },
                  { name: 'enabled', label: 'Enabled', widget: 'boolean', default: true },
                  { name: 'content', label: 'content', widget: 'string' },
                  {
                    name: 'form',
                    label: 'Form',
                    widget: 'object',
                    fields:
                      [
                        { name: 'text', label: 'Placeholder Text', widget: 'string' },
                        { name: 'button', label: 'Button Text', widget: 'string' }
                      ]
                  },
                  { name: 'image_link', label: 'Image Link', widget: 'image' },
                  { name: 'image_alt', label: 'Image Alt Text', widget: 'string' }
                ]
            }
          - {
              name: 'benefits',
              label: 'Benefits',
              widget: 'object',
              fields:
                [
                  { name: 'title', label: 'Title', widget: 'string' },
                  { name: 'enabled', label: 'Enabled', widget: 'boolean', default: true },
                  { name: 'label', label: 'label', widget: 'string' },
                  {
                    name: 'benefit',
                    label: 'Benefit',
                    widget: 'list',
                    allow_add: false,
                    fields:
                      [
                        { name: 'title', label: 'Title', widget: 'string' },
                        { name: 'content', label: 'content', widget: 'string' },
                        { name: 'image_link', label: 'Image Link', widget: 'image' },
                      ]
                  },
                ]
            }
          - {
              name: 'advantages',
              label: 'Advantages',
              widget: 'object',
              fields:
                [
                  { name: 'title', label: 'Title', widget: 'string' },
                  { name: 'enabled', label: 'Enabled', widget: 'boolean', default: true },
                  { name: 'label', label: 'label', widget: 'string' },
                  { name: 'content', label: 'content', widget: 'string' },
                  {
                    name: 'advantage',
                    label: 'Advantage',
                    widget: 'list',
                    allow_add: false,
                    fields:
                      [
                        { name: 'image_link', label: 'Image Link', widget: 'image' },
                        { name: 'content', label: 'content', widget: 'string' },
                      ]
                  },
                ]
            }
          - {
              name: 'call_to_action',
              label: 'Call to Action',
              widget: 'object',
              fields:
                [
                  { name: 'title', label: 'Title', widget: 'string' },
                  { name: 'enabled', label: 'Enabled', widget: 'boolean', default: true },
                  { name: 'content', label: 'content', widget: 'string' },
                  {
                    name: 'button',
                    label: 'Button',
                    widget: 'object',
                    fields:
                      [
                        { name: 'text', label: 'Placeholder Text', widget: 'string' },
                        { name: 'link', label: 'Link', widget: 'string' }
                      ]
                  },
                  { name: 'image_link', label: 'Image Link', widget: 'image' },
                  { name: 'image_alt', label: 'Image Alt Text', widget: 'string' }
                ]
            }
          - {
              name: 'brands',
              label: 'Brands',
              widget: 'object',
              fields:
                [
                  { name: 'title', label: 'Title', widget: 'string' },
                  { name: 'enabled', label: 'Enabled', widget: 'boolean', default: true },
                  { name: 'content', label: 'content', widget: 'string' },
                  {
                    name: 'brand',
                    label: 'Brand',
                    widget: 'list',
                    allow_add: false,
                    field: { name: 'image_link', label: 'Image Link', widget: 'image' }
                  }
                ]
            }
          - {
              name: 'offers',
              label: 'offers',
              widget: 'object',
              fields:
                [
                  { name: 'title', label: 'Title', widget: 'string' },
                  { name: 'enabled', label: 'Enabled', widget: 'boolean', default: true },
                  { name: 'label', label: 'label', widget: 'string' },
                  {
                    name: 'offer',
                    label: 'offer',
                    widget: 'list',
                    allow_add: false,
                    fields:
                      [
                        { name: 'title', label: 'Title', widget: 'string' },
                        { name: 'content', label: 'content', widget: 'string' },
                        { name: 'image_link', label: 'Image Link', widget: 'image' },
                      ]
                  },
                ]
            }
          - {
              name: 'features',
              label: 'Features',
              widget: 'object',
              fields: [
                { name: 'title', label: 'Title', widget: 'string' },
                { name: 'enabled', label: 'Enabled', widget: 'boolean', default: true },
                {
                  name: 'feature',
                  label: 'Feature',
                  widget: 'list',
                  allow_add: false,
                  fields:
                    [
                      { name: 'title', label: 'Title', widget: 'string' },
                      { name: 'content', label: 'content', widget: 'string' },
                      { name: 'image_link', label: 'Image Link', widget: 'image' },
                    ]
                },
              ]
            }
          - {
              name: 'reviews',
              label: 'Reviews',
              widget: 'object',
              fields: [
                { name: 'title', label: 'Title', widget: 'string' },
                { name: 'enabled', label: 'Enabled', widget: 'boolean', default: true },
                {
                  name: 'review',
                  label: 'Review',
                  widget: 'list',
                  allow_add: false,
                  fields:
                    [
                      { name: 'name', label: 'Name', widget: 'string' },
                      { name: 'title', label: 'Title', widget: 'string' },
                      { name: 'content', label: 'content', widget: 'string' },
                      { name: 'image_link', label: 'Image Link', widget: 'image' },
                    ]
                },
              ]
            }
          - {
              name: 'promotion',
              label: 'promotion',
              widget: 'object',
              fields:
                [
                  { name: 'title', label: 'Title', widget: 'string' },
                  { name: 'enabled', label: 'Enabled', widget: 'boolean', default: true },
                  { name: 'content', label: 'content', widget: 'string' },
                  {
                    name: 'button',
                    label: 'Button',
                    widget: 'object',
                    fields:
                      [
                        { name: 'text', label: 'Placeholder Text', widget: 'string' },
                        { name: 'link', label: 'Link', widget: 'string' }
                      ]
                  },
                ]
            }

    preview_path: /{{slug}}
